version : '3.8'

services:
  ruoyi-nacos:
    container_name: ruoyi-nacos
    image: nacos/nacos-server
    restart: always
    build:
      context: ./nacos
    env_file:
      .env
    environment:
        MODE: standalone
        SPRING_DATASOURCE_PLATFORM: mysql
        MYSQL_SERVICE_HOST: 172.30.0.10
        MYSQL_SERVICE_PORT: 3306
        MYSQL_SERVICE_USER: root
        MYSQL_SERVICE_PASSWORD: 123456
        MYSQL_SERVICE_DB_NAME: ry_cloud
        MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    volumes:
      - ./nacos/logs/:/home/nacos/logs
#      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    networks:
        ruoyi:
          ipv4_address: 172.30.0.2
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - ruoyi-mysql
  ruoyi-mysql:
    container_name: ruoyi-mysql
    image: mysql:8
    build:
      context: ./mysql
    networks:
      ruoyi:
        ipv4_address: 172.30.0.10
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'ry_cloud'

  ruoyi-redis:
    container_name: ruoyi-redis
    image: redis
    build:
      context: ./redis
    networks:
      ruoyi:
        ipv4_address: 172.30.0.20
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/ruoyi/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/ruoyi/redis/redis.conf
  ruoyi-nginx:
    container_name: ruoyi-nginx
    image: nginx
    build:
      context: ./nginx
    networks:
      ruoyi:
        ipv4_address: 172.30.0.4
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/ruoyi/projects/ruoyi-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ruoyi-gateway
    links:
      - ruoyi-gateway
  ruoyi-gateway:
    container_name: ruoyi-gateway
    env_file:
      .env
    build:
      context: ./ruoyi/gateway
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.31
    ports:
      - "7000:7000"
    depends_on:
      - ruoyi-redis
    links:
      - ruoyi-redis
  ruoyi-auth:
    container_name: ruoyi-auth
    env_file:
      .env
    build:
      context: ./ruoyi/auth
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.32
    ports:
      - "9200:9200"
    depends_on:
      - ruoyi-redis
    links:
      - ruoyi-redis
  ruoyi-modules-system:
    container_name: ruoyi-modules-system
    env_file:
      .env
    build:
      context: ./ruoyi/modules/system
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.33
    ports:
      - "9201:9201"
    depends_on:
      - ruoyi-redis
      - ruoyi-mysql
    links:
      - ruoyi-redis
      - ruoyi-mysql
  ruoyi-modules-gen:
    container_name: ruoyi-modules-gen
    env_file:
      .env
    build:
      context: ./ruoyi/modules/gen
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.34
    ports:
      - "9202:9202"
    depends_on:
      - ruoyi-mysql
    links:
      - ruoyi-mysql
  ruoyi-modules-job:
    container_name: ruoyi-modules-job
    env_file:
      .env
    build:
      context: ./ruoyi/modules/job
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.35
    ports:
      - "9203:9203"
    depends_on:
      - ruoyi-mysql
    links:
      - ruoyi-mysql
  ruoyi-modules-file:
    container_name: ruoyi-modules-file
    env_file:
      .env
    build:
      context: ./ruoyi/modules/file
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.36
    ports:
      - "9300:9300"
    volumes:
    - ./ruoyi/uploadPath:/home/ruoyi/uploadPath
  ruoyi-visual-monitor:
    container_name: ruoyi-visual-monitor
    env_file:
      .env
    build:
      context: ./ruoyi/visual/monitor
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.37
    ports:
      - "9100:9100"
  religion:
    container_name: religion
    env_file:
      .env
    build:
      context: ./ruoyi/modules/religion
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.38
    ports:
      - "9099:9099"
    depends_on:
      - ruoyi-mysql
    links:
      - ruoyi-mysql
  phone:
    container_name: phone
    env_file:
      .env
    build:
      context: ./ruoyi/modules/phone
      dockerfile: dockerfile
    networks:
      ruoyi:
        ipv4_address: 172.30.0.39
    ports:
      - "9210:9210"
    depends_on:
      - ruoyi-mysql
    links:
      - ruoyi-mysql
networks:
  ruoyi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24